### ISSUE TITLE
Natural language processing

### ISSUE THREAD

**Issue by exerro** [SquidDev-CC/artist#6]
Sometimes the GUI will be a pain to operate, and you might be away from the base when you want to start crafting things. Natural language processing, combined with networked PDAs, chatboxes, and direct text input, would give a powerful way of communicating with the item server.

Some examples of phrases:
- `craft some repeaters`
- `get 5 stacks of cyan stained clay ready`
- `put some seeds in the farm chest`
- `craft torches when there's less than 32 left`

**Comment by Lupus590** [comment]
While true natural language processing would be very complex (and maybe pushing the limit of what Lua can do), having a command line with a fixed structure to commands sounds possible. This could then be implemented over networks. chatboxes etc.
